name: tests

on: [push, pull_request]

env:
  PHP_CS_FIXER_IGNORE_ENV: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 15
      matrix:
        os: [ ubuntu-latest ]
        php: [ "8.0", "8.1", "8.2" ]

    name: PHP ${{ matrix.php }} Test on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, bcmath
          tools: phpize
          coverage: none

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Check PHP Extensions
        run: php -m

      - name: Install Dependencies
        run: composer install --dev

      - name: Run Cs Fixer
        run: composer fix-cs

      - name: Run PHPStan
        run: composer phpstan

      # - name: Run Test
      #   run: composer test
